spring.application.name=selfmade

# DB ??
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:selfmade}
spring.datasource.username=${POSTGRES_USER:siwoo}
spring.datasource.password=${POSTGRES_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=helloiwannabeabackenddeveloperpleasehelpmetobeadeveloperthatismyhope
jwt.access-token-expiration=1800000
jwt.refresh-token-expiration=604800000
# access token - 30분 / refresh token - 7일

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}